In [1]:
import numpy as np

In [45]:
array1=np.array([1,2,3])
array2=np.array([[1.,2.,3.],
                 [4,5,6.]])
array3=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])

array_list=[array1,array2,array3]

In [49]:
def shape_ndarray(x):
    
    a=x.shape
    b=x.ndim
    c=x.dtype #타입변경: array.astype('변경타입')
    return print(f'{x} \n차원: {b}차원 \n형태: {a} \n데이터타입: {c}' +'\n', '='*10 +'\n')


for x in array_list:
    shape_ndarray(x)

[1 2 3] 
차원: 1차원 
형태: (3,) 
데이터타입: int64

[[1. 2. 3.]
 [4. 5. 6.]] 
차원: 2차원 
형태: (2, 3) 
데이터타입: float64

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 
차원: 3차원 
형태: (1, 3, 3) 
데이터타입: int64



In [60]:
#간편생성 : arange, zeros, ones

a= np.arange(10)
b= np.arange(5,10)

print(a,'\n',b)

[0 1 2 3 4 5 6 7 8 9] 
 [5 6 7 8 9]


In [64]:
#zeros : dtype 설정해야함
c=np.zeros((2,3),dtype='int32')

print(c, c.dtype)

[[0 0 0]
 [0 0 0]] int32


In [66]:
#ones
d=np.ones((3,3),dtype='float64')

print(d, d.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64
